/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary": "#adc6ff",
                "on-primary": "#002e6a",
                "primary-container": "#4d8eff",
                "on-primary-container": "#00285d",
                "inverse-primary": "#005ac2",
                "secondary": "#d0bcff",
                "on-secondary": "#3c0091",
                "secondary-container": "#571bc1",
                "on-secondary-container": "#c4abff",
                "tertiary": "#4edea3",
                "on-tertiary": "#003824",
                "tertiary-container": "#00a572",
                "on-tertiary-container": "#00311f",
                "error": "#ffb4ab",
                "on-error": "#690005",
                "error-container": "#93000a",
                "on-error-container": "#ffdad6",
                "primary-fixed": "#d8e2ff",
                "primary-fixed-dim": "#adc6ff",
                "on-primary-fixed": "#001a42",
                "on-primary-fixed-variant": "#004395",
                "secondary-fixed": "#e9ddff",
                "secondary-fixed-dim": "#d0bcff",
                "on-secondary-fixed": "#23005c",
                "on-secondary-fixed-variant": "#5516be",
                "tertiary-fixed": "#6ffbbe",
                "tertiary-fixed-dim": "#4edea3",
                "on-tertiary-fixed": "#002113",
                "on-tertiary-fixed-variant": "#005236",
                "surface": "#10131a",
                "surface-dim": "#10131a",
                "surface-bright": "#363941",
                "surface-container-lowest": "#0b0e15",
                "surface-container-low": "#191b23",
                "surface-container": "#1d2027",
                "surface-container-high": "#272a31",
                "surface-container-highest": "#32353c",
                "on-surface": "#e1e2ec",
                "on-surface-variant": "#c2c6d6",
                "inverse-surface": "#e1e2ec",
                "inverse-on-surface": "#2e3038",
                "outline": "#8c909f",
                "outline-variant": "#424754",
                "surface-tint": "#adc6ff",
                "background": "#10131a",
                "on-background": "#e1e2ec",
                "surface-variant": "#32353c"
            },
            fontFamily: {
                sans: ["Inter", "sans-serif"],
                "headline-xl": ["Inter", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                "display-lg": ["Inter", "sans-serif"],
                "headline-lg": ["Inter", "sans-serif"],
                "button": ["Inter", "sans-serif"],
                "label-md": ["Inter", "sans-serif"],
                "headline-md": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"]
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
}
