/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary": "#d2bbff",
                "primary-container": "#7c3aed",
                "error": "#ffb4ab",
                "primary-fixed": "#eaddff",
                "tertiary": "#00dbe7",
                "on-primary-fixed": "#25005a",
                "on-error": "#690005",
                "on-secondary-container": "#b3b1ff",
                "inverse-on-surface": "#283044",
                "on-tertiary-fixed-variant": "#004f54",
                "tertiary-container": "#007279",
                "on-primary": "#3f008e",
                "secondary-container": "#3626ce",
                "on-tertiary-container": "#8af6ff",
                "surface-bright": "#31394d",
                "secondary-fixed-dim": "#c3c0ff",
                "on-primary-fixed-variant": "#5a00c6",
                "error-container": "#93000a",
                "background": "#0b1326",
                "primary-fixed-dim": "#d2bbff",
                "on-surface": "#dae2fd",
                "surface-tint": "#d2bbff",
                "on-tertiary-fixed": "#002022",
                "surface-container-low": "#131b2e",
                "inverse-primary": "#732ee4",
                "surface-container-highest": "#2d3449",
                "on-surface-variant": "#ccc3d8",
                "tertiary-fixed": "#74f5ff",
                "surface-container-high": "#222a3d",
                "secondary-fixed": "#e2dfff",
                "secondary": "#c3c0ff",
                "surface-container-lowest": "#060e20",
                "on-background": "#dae2fd",
                "on-primary-container": "#ede0ff",
                "surface-variant": "#2d3449",
                "surface-dim": "#0b1326",
                "inverse-surface": "#dae2fd",
                "on-secondary-fixed-variant": "#3323cc",
                "surface-container": "#171f33",
                "on-tertiary": "#00363a",
                "tertiary-fixed-dim": "#00dbe7",
                "on-secondary": "#1d00a5",
                "outline-variant": "#4a4455",
                "surface": "#0b1326",
                "outline": "#958da1",
                "on-error-container": "#ffdad6",
                "on-secondary-fixed": "#0f0069"
            },
            fontFamily: {
                "headline-xl": ["Epilogue"],
                "body-lg": ["Be Vietnam Pro"],
                "display-lg": ["Epilogue"],
                "headline-lg": ["Epilogue"],
                "button": ["Space Grotesk"],
                "label-md": ["Space Grotesk"],
                "headline-md": ["Epilogue"],
                "body-md": ["Be Vietnam Pro"]
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
}
