// src/constants/initialClasses.ts — Satranç Bölümünden Çözülen Okul Sınıfları ve Öğrenci Kadroları
import type { ClassRoom } from '../types/classroom';

export const INITIAL_CLASSES: ClassRoom[] = [
    {
        id: 'c46f39bd64255a2',
        name: '2-Kerkük',
        username: '2kerkuk',
        password: '1234',
        grade: '2',
        assignedModules: ['satranc', 'deneyler', 'akil-oyunlari', 'kodlama'],
        assignedExperiments: ['basit-pusula.html', 'isildayan-devre.html', 'termometre.html', 'golge-oyunu.html'],
        assignedNotebooks: [],
        assignedActivities: [],
        students: [
            { id: 's7cc0870859724f', name: 'Ali Alpertunga Şık' },
            { id: 's5a33e4da6a3c54', name: 'Ansar Jexengaliyeva' },
            { id: 'sb22bce8ab07d86', name: 'Ayşe Hafsa Nalbantlı' },
            { id: 's9db5823888319b', name: 'Ayşe Vera Aydın' },
            { id: 'sf0134701df685f', name: 'Elif Şifa Erbay' },
            { id: 'sc5e0127aefcc51', name: 'Erva Doğan' },
            { id: 'sc979e1cffb2e5e', name: 'Eylül Elif Yiğit' },
            { id: 's50dd1d639e1ce0', name: 'Fatıma Şişman' },
            { id: 's044a46757fbb8c', name: 'Mehmed Hilmi Başköy' },
            { id: 's3f08298675453c', name: 'Ömer Asaf Çeliker' },
        ],
    },
    {
        id: 'c23913a8b925e39',
        name: '2-Taşkent',
        username: '2taskent',
        password: '1234',
        grade: '2',
        assignedModules: ['satranc', 'deneyler', 'akil-oyunlari', 'kodlama'],
        assignedExperiments: ['basit-pusula.html', 'isildayan-devre.html', 'termometre.html', 'golge-oyunu.html'],
        assignedNotebooks: [],
        assignedActivities: [],
        students: [
            { id: 'sd510a0f4290668', name: 'Ahmet Kürşat Şayin' },
            { id: 's90e30d767c4fec', name: 'Bihan Deren Karahan' },
            { id: 's8255128adb435e', name: 'Elif Lina Elitaş' },
            { id: 's70faef2397dc56', name: 'Kutlu Zeynep Özçelik' },
            { id: 'saadecc7bd87d1d', name: 'Mehmet Emir Özdemir' },
            { id: 'sf786fc365cb938', name: 'Mehmet Salih Şahiner' },
            { id: 's772f9d854ec779', name: 'Meryem Hüma Taşkan' },
            { id: 's41e069150ea31d', name: 'Muhammet Selman Yayla' },
            { id: 'sb6f1e948c26359', name: 'Mustafa Selim Mıhoğlu' },
            { id: 's273f55eb45785a', name: 'Ömer Cebeci' },
            { id: 's1507df04473347', name: 'Rukiye Yaşar' },
            { id: 's5be373b9e59885', name: 'Zeynep Azra Sevsevil' },
        ],
    },
    {
        id: 'c9ab8346b9b34b1',
        name: '2-Üsküp',
        username: '2uskup',
        password: '1234',
        grade: '2',
        assignedModules: ['satranc', 'deneyler', 'akil-oyunlari', 'kodlama'],
        assignedExperiments: ['basit-pusula.html', 'isildayan-devre.html', 'termometre.html', 'golge-oyunu.html'],
        assignedNotebooks: [],
        assignedActivities: [],
        students: [
            { id: 'sa09a5eb4082845', name: 'Abdullah Kerem Genç' },
            { id: 's1dfdb9ad2dc4bf', name: 'Ali Özatağ' },
            { id: 's07842ef8f514b8', name: 'Emir Uraz Işık' },
            { id: 's90e4a78fa8f8aa', name: 'Esma Tüfekçi' },
            { id: 'sb7107c1341c2c8', name: 'Hafsa Vera Dilmaç' },
            { id: 'sae215456f9ff2f', name: 'Lale Benan Doğan' },
            { id: 'sb596395b05a766', name: 'Mehmet Aras Güneş' },
            { id: 's2e11a3df3ec3df', name: 'Muhammed Şems Aydemir' },
            { id: 's0bf323c28da55a', name: 'Selim Affan Erdoğan' },
            { id: 'sf3e0e7a2df2da5', name: 'Serra Naz Pazarbaşı' },
            { id: 's7a8c3d9a10243e', name: 'Zeynep Duru Çıtır' },
        ],
    },
    {
        id: 'c92fa5c30cf8bf0',
        name: '3-Ali Kuşçu',
        username: '3alikuscu',
        password: '1234',
        grade: '3',
        assignedModules: ['satranc', 'deneyler', 'akil-oyunlari', 'kodlama', 'gunes-sistemi'],
        assignedExperiments: ['basit-pusula.html', 'isildayan-devre.html', 'surtunme-kuvveti.html', 'renk-kulesi.html'],
        assignedNotebooks: [],
        assignedActivities: [],
        students: [
            { id: 'sb559c5d0705a61', name: 'Ahmet Asaf Aytemür' },
            { id: 's032fa6c729574f', name: 'Ali Asaf Öz' },
            { id: 's3ffcf60a340625', name: 'Ali Asaf Sarğut' },
            { id: 's6eb8df84d1421f', name: 'Amine Günbala Altındağ' },
            { id: 's026a761eb8bf29', name: 'Ayşe Seray Cevahir' },
            { id: 's1c3569769da8a5', name: 'Ayşe Serra Çolak' },
            { id: 'sd5ca6ca1ae536b', name: 'Betül İlbilge Nazlım' },
            { id: 's3b6ea2a71d798a', name: 'Emre Güler' },
            { id: 's6109df50d603e8', name: 'Eymen Belli' },
            { id: 'sf4186ef957777f', name: 'Hasan Eren Erünsal' },
            { id: 'sa40728c0dbd06a', name: 'Hifa Kartal' },
            { id: 'seba42d655f466b', name: 'Mir Hamza Çiftçi' },
            { id: 'scfa89150074212', name: 'Muaz Ömer Topcu' },
            { id: 's7c4ffcba829ec9', name: 'Nazenin Arda' },
            { id: 'sf537f59424269e', name: 'Oktay Hakan Bayram' },
            { id: 's4169562dc6ec30', name: 'Yusuf Koç' },
        ],
    },
    {
        id: 'c4ddee39f33b256',
        name: '3-Bilge Kağan',
        username: '3bilgekagan',
        password: '1234',
        grade: '3',
        assignedModules: ['satranc', 'deneyler', 'akil-oyunlari', 'kodlama', 'gunes-sistemi'],
        assignedExperiments: ['basit-pusula.html', 'isildayan-devre.html', 'surtunme-kuvveti.html', 'renk-kulesi.html'],
        assignedNotebooks: [],
        assignedActivities: [],
        students: [
            { id: 'sc895cf38b41ca7', name: 'Ahmet Mansur Bilge' },
            { id: 's9a13917452d3a3', name: 'Ahmet Selim Mutlu' },
            { id: 'sb755694a123f14', name: 'Ali Aslan' },
            { id: 's425f190cbb40ef', name: 'Assan Jexengaliyeva' },
            { id: 'sdbf614ad26fe66', name: 'Ayşe Leyla Ay' },
            { id: 's819ecfe761be5c', name: 'Ayşe Sena Doğan' },
            { id: 's54bf90ec826359', name: 'Emirhan Duygun' },
            { id: 'sebe6777aa05658', name: 'Halid Affan Yıldız' },
            { id: 'sb5697241cfda4a', name: 'Havin Yücetürk' },
            { id: 's9bc44d7159f81a', name: 'Melike Zehra Bacıoğlu' },
            { id: 's50baec6a41499f', name: 'Muaz Taha Coşkun' },
            { id: 's93e8a71954ca5a', name: 'Muhammed Mirza Korkmaz' },
            { id: 's3ff65063071bb2', name: 'Rana Bozacıoğlu' },
            { id: 's7a82743a183570', name: 'Tahir Alp Kütükcü' },
            { id: 'sb59bbd0dc522e8', name: 'Yunus Emre Kaplan' },
        ],
    },
    {
        id: 'c721a59ea645c6c',
        name: '4-İbni Sina',
        username: '4ibnisina',
        password: '1234',
        grade: '4',
        assignedModules: ['satranc', 'deneyler', 'akil-oyunlari', 'kodlama', 'insan-vucudu', 'gunes-sistemi'],
        assignedExperiments: ['vucudumuzu-taniyalim.html', 'kalbimiz-kani-pompaliyor.html', 'balonlu-itme-araci.html', 'isildayan-devre.html'],
        assignedNotebooks: [],
        assignedActivities: [],
        students: [
            { id: 's58410260dbba93', name: 'Ahmet Akdoğan' },
            { id: 's8b76dfb3dafc57', name: 'Ahmet Yaşar Küçük' },
            { id: 's932822a106e232', name: 'Ali Ertuğrul Kürüm' },
            { id: 'sb4ef4ae3863482', name: 'Banah Alruhban' },
            { id: 'se78e72793132bc', name: 'Burak Arda' },
            { id: 's311ebc4be486a4', name: 'Elif Hüma Başköylü' },
            { id: 'seba766c6b45452', name: 'Elif Neva Torlak' },
            { id: 'se7444b055938f3', name: 'Eslem Doğan' },
            { id: 'sd5a557b77ab67f', name: 'Eslem Şehnaz Demiralp' },
            { id: 's10a6231ebc4bf1', name: 'Eymen Burak Tekin' },
            { id: 's07db815b8fb0f1', name: 'Hüseyin Emre Özdemir' },
            { id: 's41e1ea2ba64024', name: 'İlhan Yamakoğlu' },
            { id: 's365ecfa46abfe1', name: 'Nisa Azaklı' },
            { id: 'se67db51147ee19', name: 'Ömer Faruk Kartal' },
            { id: 's02b545fba2665e', name: 'Ömer Hakkı Boran' },
            { id: 's04b4cf47116a8a', name: 'Serdar Orazgeldiyev' },
            { id: 's2c3e414cda71b4', name: 'Yahya Ömer Çelik' },
        ],
    },
    {
        id: 'c0a3c0d94e67f37',
        name: '4-Uluğbey',
        username: '4ulugbey',
        password: '1234',
        grade: '4',
        assignedModules: ['satranc', 'deneyler', 'akil-oyunlari', 'kodlama', 'gunes-sistemi', 'geometri'],
        assignedExperiments: ['gunes-ve-golge.html', 'basit-pusula.html', 'isildayan-devre.html', 'balonlu-itme-araci.html'],
        assignedNotebooks: [],
        assignedActivities: [],
        students: [
            { id: 'se84ef53a1a4fe8', name: 'Ahmet Erdem Şahiner' },
            { id: 'sae086ab2c61aa0', name: 'Ahmet Fatih İşcan' },
            { id: 's21245fa7883d6a', name: 'Ahmet Hira Sönmez' },
            { id: 's63d59663ea534c', name: 'Ali Muaz Ayrancıoğlu' },
            { id: 's6eb54e0c3453ea', name: 'Amine Duru Ergün' },
            { id: 's403e9ebdb81a95', name: 'Bilgehatun Bilgili' },
            { id: 'sb6ea8c85c2759e', name: 'Enfal Muhammed Demiralp' },
            { id: 's88a4ba1e5ef621', name: 'Ertuğrul Alp Çelik' },
            { id: 's19eb6085a1ef0c', name: 'Gülru Ergincan' },
            { id: 's47ee4587db3bb3', name: 'Halit Emir Bayram' },
            { id: 'scfa709b1ea6fb2', name: 'Hamza Fatih İmre' },
            { id: 's7a8f331adba75e', name: 'Hira Nur Doğan' },
            { id: 'sa18f506822a106', name: 'Hüma Akdoğan' },
            { id: 'sbdf6c71beba318', name: 'Hüma Sare Laçin' },
            { id: 's892ba475efba82', name: 'Muhammed Şişman' },
        ],
    },
];
