export const scienceCases=[
 {name:'Solan fasulyeler',story:'Aynı tür fasulyelerden pencere kenarındakiler soldu. Sulama mı, ışık mı, toprak mı? Bir iddiayı seçmeden önce karşılaştırmalı deneyler yap.',hypotheses:['Su eksikliği','Işık eksikliği','Toprak türü'],answer:0,tests:[
 ['Nem ölçümü',12,'İki saksı aynı ışıkta. Solan saksıda nem %12, sağlıklı saksıda %48.',[12,48],'Toprak nemi (%)'],
 ['Kontrollü sulama',20,'Aynı ışık, toprak ve tür; yalnız su değişti. 3 günde sulanan grubun 8/10, sulanmayan grubun 1/10 fidesi toparlandı.',[8,1],'Toparlanan fide'],
 ['Işık deneyi',18,'Su ve toprak eşit. Orta ve yüksek ışıkta 8/10 fide toparlandı. Bu aralıkta ışık farkı sonucu açıklamıyor.',[8,8],'Toparlanan fide'],
 ['Toprak karşılaştırması',18,'Su ve ışık eşit. İki toprakta da 8/10 fide toparlandı.',[8,8],'Toparlanan fide']],required:[0,1],control:'Işık, toprak, bitki türü',controls:['Işık, toprak, bitki türü','Su miktarı','Yalnız saksı rengi'],conclusion:'Bu deneylerde su eksikliği açıklaması desteklendi. Başka koşullarda başka nedenler olabilir.'},
 {name:'Paslanan köprü örnekleri',story:'Köprüden alınan eş çelik parçaları laboratuvarda karşılaştır. Tuzlu su, kuru hava ve boya kaplaması neyi değiştiriyor?',hypotheses:['Tuzlu su paslanmayı hızlandırıyor','Kuru hava daha hızlı paslandırıyor','Boya pası artırıyor'],answer:0,tests:[['Kuru / nemli ortam',15,'Aynı çelik ve süre: kuru ortamda 1, nemli ortamda 5 birim paslı alan.',[1,5],'Paslı alan (oyun birimi)'],['Tatlı / tuzlu su',20,'Aynı çelik, sıcaklık ve süre: tatlı suda 5, tuzlu suda 9 birim paslı alan.',[5,9],'Paslı alan'],['Boyalı / boyasız',20,'Tuzlu su ve süre aynı: sağlam boya altında 1, boyasız yüzeyde 9 birim pas.',[1,9],'Paslı alan'],['Parça büyüklüğü',10,'Büyük ve küçük örneklerde toplam alan farklı. Alan oranı olmadan adil karşılaştırma yapılamaz.',[8,4],'Ham alan; kıyas için yetersiz']],required:[0,1],control:'Çelik türü, sıcaklık, süre',controls:['Çelik türü, sıcaklık, süre','Tuz miktarı','Sadece renk'],conclusion:'Tuzlu su bu koşullarda korozyonu hızlandırdı. Sağlam kaplama yüzeyin su ve oksijenle temasını azaltabilir.'},
 {name:'Yeşile dönen gölet',story:'Gölet yakınındaki bir tarladan yağmur sonrası su akıyor. Alg artışının olası nedenini kontrollü örneklerle araştır.',hypotheses:['Besin tuzlarının artması','Suyun renginin kendiliğinden değişmesi','Taş sayısının artması'],answer:0,tests:[['Su örneği analizi',15,'Tarla çıkışında nitrat 8, üst akışta 2 oyun birimi. Bu tek başına nedensellik göstermez.',[8,2],'Nitrat (oyun birimi)'],['Kontrollü besin deneyi',20,'Işık, sıcaklık ve başlangıç algi eşit. Besin eklenen kapta alg 9, kontrol kabında 3 birim.',[9,3],'Alg miktarı'],['Gündüz / gece oksijeni',15,'Yoğun alg bulunan kapta oksijen gündüz 8, gece 3 birim. Canlılar gece de solunum yapar.',[8,3],'Oksijen (oyun birimi)'],['Taş ekleme deneyi',15,'Diğer koşullar eşit; taş eklemek alg miktarını değiştirmedi.',[3,3],'Alg miktarı']],required:[0,1],control:'Işık, sıcaklık, başlangıç algi',controls:['Işık, sıcaklık, başlangıç algi','Eklenen besin miktarı','Yalnız su rengi'],conclusion:'Besin tuzu artışı alg çoğalmasını destekledi. Kaynak tespiti için daha uzun süreli örnekleme gerekir.'}
];
export const forensicCases=[
 {name:'Müzedeki kayıp etiket',story:'Bir sergi etiketi yanlış depoya gönderilmiş. Etiketteki mürekkebi A, B ve C çalışma masalarının kalemleriyle karşılaştır. Kimseyi suçlamadan eşleşen örneği bul.',hypotheses:['A örneğiyle uyumlu','B örneğiyle uyumlu','C örneğiyle uyumlu'],answer:1,tests:[['Kromatografi',20,'Aynı çözücüde renk bantları: bilinmeyen [2,5,8], A [2,4], B [2,5,8], C [3,7].',[2,5,8],'Bilinmeyen örneğin bant konumları'],['B örneğini tekrar ölç',15,'İkinci ölçümde bilinmeyen ve B yine aynı üç bant verdi.',[2,5,8],'Tekrar ölçüm bantları'],['Görünür renk',8,'Bütün mürekkepler gözle siyah görünüyor. Renk tek başına ayırt edici değil.',[5,5,5],'Görünür renk benzerliği'],['Kâğıt incelemesi',12,'Etiket ve üç masa aynı kâğıt türünü kullanıyor.',[4,4,4],'Lif benzerliği']],required:[0,1],control:'Aynı çözücü, kâğıt ve koşma süresi',controls:['Aynı çözücü, kâğıt ve koşma süresi','Farklı çözücü kullanmak','Yalnız aynı kalem rengi'],conclusion:'Mürekkep B ile uyumlu. Aynı tür kalemi birden fazla kişi kullanabilir; kişi veya niyet belirlenemez.'},
 {name:'Gizemli mineral kutusu',story:'Müzeye gelen üç mineral kutusunun etiketi karışmış. Bilinmeyen örneği yoğunluk ve manyetik özellikleriyle eşleştir. A: 2,7 ve manyetik değil; B: 7,8 ve manyetik; C: 8,9 ve manyetik değil.',hypotheses:['A kutusu','B kutusu','C kutusu'],answer:1,tests:[['Kütle ve hacim',20,'Kütle 78 g, su taşırma ile hacim 10 cm³. Yoğunluk = 78 / 10 = 7,8 g/cm³.',[78,10],'Kütle / hacim (farklı birimler)'],['Mıknatıs testi',12,'Örnek mıknatıs tarafından belirgin biçimde çekildi.',[1,0],'Çekildi / çekilmedi'],['İkinci parça',18,'Aynı kutudan ikinci parçanın kütlesi 39 g, hacmi 5 cm³; yoğunluk yine 7,8 g/cm³.',[39,5],'Tekrar: kütle / hacim'],['Renk kontrolü',8,'A ve B benzer gri renkte; renk tek başına yeterli değil.',[5,5,2],'Görsel benzerlik']],required:[0,1],control:'Kalibre terazi ve doğru hacim ölçümü',controls:['Kalibre terazi ve doğru hacim ölçümü','Eşit renk','Sadece büyük parçayı seçmek'],conclusion:'Yoğunluk ve manyetik davranış B ile uyumlu. Bu özellikler tek başına örneğin saf bir element olduğunu kanıtlamaz.'},
 {name:'Seradaki toprak izi',story:'Araştırma arabasının tekerleğinde toprak var. A alanı kumlu (pH 7), B killi (pH 6), C organik (pH 5). Örneğin hangi alanla uyumlu olduğunu araştır.',hypotheses:['A alanı','B alanı','C alanı'],answer:2,tests:[['pH ölçümü',15,'Aynı toprak/su oranında bilinmeyen pH 5, A 7, B 6, C 5.',[5,7,6,5],'pH (logaritmik ölçek)'],['Büyüteçle inceleme',15,'Bilinmeyende ve C’de bol bitki kalıntısı var; A kumlu, B ince killi.',[8,1,2,8],'Bitki kalıntısı puanı'],['Tekrar örnekleme',18,'Üç alt örnekte pH 5,0; 5,1; 4,9 bulundu. Sonuçlar birbirine yakın.',[5,5.1,4.9],'pH tekrarları'],['İz genişliği',8,'Tekerlek genişliği biliniyor ama toprağın kaynağını ayırt etmiyor.',[6,6,6],'İz genişliği']],required:[0,1],control:'Aynı toprak/su oranı ve temiz araçlar',controls:['Aynı toprak/su oranı ve temiz araçlar','Farklı miktarda su','Yalnız aynı kap rengi'],conclusion:'Örnek C alanıyla uyumlu. Benzer toprak başka alanlarda da bulunabilir; kesin rota çıkarılamaz.'}
];
