// Deterministic educational models. Values are game units, not engineering forecasts.
export const plants={solar:{name:'Güneş',icon:'☀️',cost:25,output:14,carbon:0},wind:{name:'Rüzgâr',icon:'🌬️',cost:30,output:12,carbon:0},hydro:{name:'Hidro',icon:'💧',cost:38,output:14,carbon:0},gas:{name:'Gaz',icon:'🔥',cost:20,output:20,carbon:8},battery:{name:'Batarya',icon:'🔋',cost:20,output:0,carbon:0}};
export const gridMissions=[{name:'Kasabanın ilk şebekesi',budget:155,demand:23,carbon:80},{name:'Hastanenin gece nöbeti',budget:180,demand:29,carbon:65},{name:'Düşük karbonlu şehir',budget:210,demand:34,carbon:28}];
export function energyStep(board,turn,stored,mission){const hour=(turn*3+6)%24,sun=Math.max(0,Math.sin((hour-6)/12*Math.PI)),wind=[.8,1,.5,.7,1,.6,.4,.9][turn],demand=mission.demand+[0,3,5,1,8,5,-2,-5][turn];let production=0,carbon=0,capacity=0;board.forEach(p=>{if(!p)return;if(p==='battery'){capacity+=25;return}production+=plants[p].output*(p==='solar'?sun:p==='wind'?wind:1);carbon+=plants[p].carbon});const delta=production-demand;let shortage=0;if(delta>=0)stored=Math.min(capacity,stored+delta*.9);else{const discharge=Math.min(stored,-delta);stored-=discharge;shortage=-delta-discharge}return{hour,sun,wind,demand,production,stored,shortage,carbon,capacity}}
export const moonMissions=[{name:'İlk yerleşim',days:6,power:9},{name:'Toz fırtınası',days:8,power:9},{name:'Uzun görev',days:10,power:10}];
export function moonStep(r,a,day,mission){const dust=mission>0&&day>=2&&day<=4;return{oxygen:Math.min(100,r.oxygen-16+a.oxygen*7),water:Math.min(100,r.water-12+a.water*6-a.garden*2),food:Math.min(100,r.food-9+a.garden*5),heat:Math.min(100,r.heat-(dust?18:13)+a.heat*7),battery:Math.min(35,r.battery+(dust?6:moonMissions[mission].power)-Object.values(a).reduce((s,v)=>s+v,0))}}
export const cellMissions=[{name:'Protein siparişi',orders:3,energy:30,plant:false},{name:'Yoğun üretim',orders:5,energy:24,plant:false},{name:'Bitki hücresi',orders:6,energy:20,plant:true}];
export const organelles={nucleus:['🧬','Çekirdek','DNA’daki bilgiye göre üretim talimatı hazırlar.'],ribosome:['⚙️','Ribozom','Amino asitlerden protein sentezler.'],er:['〰️','Endoplazmik retikulum','Bu görevde salgı proteinlerinin işlenmesine ve taşınmasına katılır.'],golgi:['📦','Golgi aygıtı','Proteinleri değiştirir, sınıflandırır ve paketler.'],membrane:['🚪','Hücre zarı','Maddelerin giriş çıkışını düzenler; paket dışarı salgılanır.'],mitochondria:['⚡','Mitokondri','Besinlerin enerjisini hücrenin kullanabileceği ATP’ye aktarır.'],chloroplast:['🌿','Kloroplast','Işık enerjisiyle şeker üretir.'],lysosome:['♻️','Lizozom','Bu hayvan hücresi modelinde bozuk ürünleri parçalar.']};
export const route=['nucleus','ribosome','er','golgi','membrane'];
